# Generated by Django 4.2.2 on 2023-10-09 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PNF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_alfanumerico', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pnf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecavirtual.pnf')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateField()),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecavirtual.editorial')),
                ('pnf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecavirtual.pnf')),
                ('tipo_de_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecavirtual.tipodelibro')),
            ],
        ),
        migrations.CreateModel(
            name='Descarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_descarga', models.DateTimeField(auto_now_add=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecavirtual.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecavirtual.usuario')),
            ],
        ),
    ]
